version: '3'

services:
  fractal_test:
    build: .
    command: make run
    volumes:
      - .:/var/www/fractal_test
      - bundle-data:/var/www/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
      - redis
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200


  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
  #   environment:
  #     - xpack.security.enabled=false
  #     - xpack.monitoring.enabled=false
  #   ports:
  #     - "9300:9300"
  #   volumes:
  #     - "es-data:/usr/share/elasticsearch/data"

  elasticsearch:
    # docker run -d -p 9200:9200 -v "$PWD/esdata":/usr/share/elasticsearch/data elasticsearch
    image: elasticsearch
    ports:
      - "9200:9200"

  postgresdb:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env.development

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  sidekiq:
    command: make sidekiq
    volumes:
      - .:/var/www/fractal_test
      - bundle-data:/var/www/bundle
    depends_on:
      - 'postgresdb'
      - 'redis'
      - 'elasticsearch'
    build: .

  swaggereditor:
    image: swaggerapi/swagger-editor
    ports:
      - "8080:8080"

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  bundle-data:
    driver: local
